# -*- coding: utf-8 -*-
"""Emotion_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1deseV8iXPYV9GTTpN6TuC2Mzzwk24oHe
"""

from google.colab import files

uploaded = files.upload()

import zipfile

with zipfile.ZipFile("Audio_Speech_Actors_01-24.zip", 'r') as zip_ref:
    zip_ref.extractall("ravdess_audio")

import os
os.listdir("ravdess_audio")

!pip install librosa
!pip install soundfile
!pip install tensorflow

emotion_map = {
    '01': 'Confident',
    '02': 'Confident',
    '03': 'Confident',
    '04': 'Nervous',
    '05': 'Nervous',
    '06': 'Nervous',
    '07': 'Nervous',
    '08': 'Nervous'
}

def get_label(filename):
    emotion_code = filename.split("-")[2]
    return 0 if emotion_map[emotion_code] == "Confident" else 1

import librosa
import numpy as np

def extract_features(file_path, n_mfcc=40):
    y, sr = librosa.load(file_path, duration=3)
    #mfcc : tone and timbre of the voice
    mfccs = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=n_mfcc)
    mfccs = np.mean(mfccs.T, axis=0)

    # pitch
    pitches, magnitudes = librosa.piptrack(y=y, sr=sr)
    pitch = np.mean(pitches)

    # energy
    energy = np.mean(librosa.feature.rms(y=y))

    return np.hstack([mfccs, pitch, energy])

X, y = [], []

for root, dirs, files in os.walk("ravdess_audio"):
    for file in files:
        if file.endswith(".wav"):
            file_path = os.path.join(root, file)
            features = extract_features(file_path)
            label = get_label(file)
            X.append(features)
            y.append(label)

X = np.array(X)
y = np.array(y)
print("X shape:", X.shape)
print("y shape:", y.shape)

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, Dense, Flatten, Dropout

# CNN Model
X_cnn = X[..., np.newaxis]

model = Sequential([
    Conv1D(64, 3, activation='relu', input_shape=(X_cnn.shape[1], 1)),
    Dropout(0.3),
    Conv1D(128, 3, activation='relu'),
    Flatten(),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

model.fit(X_cnn, y, epochs=30, batch_size=32, validation_split=0.2)

test_file = "ravdess_audio/Actor_01/03-01-01-01-01-01-01.wav"
features = extract_features(test_file)
features = features[np.newaxis, ..., np.newaxis]

confidence = model.predict(features)[0][0]
print(f"Confidence score (0–1): {confidence:.2f}")